travis:
  secure:
    BINSTAR_TOKEN: JAF3/KBVyQGIsat/VjIU2vIMfqKDudvswcv9pSwRpD25CTcFt8qnIAaL2G9oe8F2jBRTztIFlfwGkk60kz7r3+JWw8g6/qU+faw2hYyYJjfrUNSEdRzxzfrV16j2txhpvl4qanzR9paoYHrKxkXvpGRZJYuFhzM/lzeoQSVa7yump1YWo56eKAmVWHzixWzRkleB2AR0Zb/DYxK9Rcj9YMj/ZJfNOLcsEjXGIMNjzmvJ/VudHmBmWeHtkd29+QOvQsQ0c2a/aXQouJVnMqyS/K79sDDH2U+gexLAg3nsR6o1OZXnRBj+hoGmRDLuTmRB93sb+axm1wZJDUNkUC+h+0D5eFbXNNbV5iXquV7vNe2UYxfOOsZL0Fskv+iOu+28PrCPgCDh5GMbHwWSyslEFvfz0hU9tfU3b03Tnn32W057Gr2RZ0avKS8Z3MzQ4q7uNPXC18+vAfCukzzE0ENSS7ARlJFsJEZ/LoCq+8PcmLOKrzYFbvGipicrFjS1HJsJ0W2onQ4/Kc7EWSUwcBoEp898Fh31g4SLo4f4mBm9etlbqQ000U5FxSmpYFf2yW/0KOg0g+Mafkba7uqTfttJZEM6B+108Xbzhf7Ojh+qDajmks5jHUsagHtena3KGrRj8JnhXS7P6PV7U9DyMaKCLxbMhcgDePBhzehSEdlfS70=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
