travis:
  secure:
    BINSTAR_TOKEN: ACgtLeoGk98bm42//xLgLpHWfldm1ANUuttmeblbNJ4lbOOWUktbKfgqfpU3RFx8vI0KuS8FsCznmI3oBb1GUZknIl8xz7Scx07KIJeafQuWaa3GpxexWbl/l2MB9B+2Oeu97xfXzsVhRmsTtwSFwq8D6WMuETyRFTv0Dgalqd/JOzW0cD7j/9adHmKt89rG/rMSxjD6/TPY11MRigeYt7lwH+Kq487iQoHim+ewSfZ6Z42q0GniHUS6z66sWPMluGcvR7sgyomA/Yi3m+30flmAyI+ofCSkoNrG8slfXiHBV8yqBgmDV+aIeKYV/0gQlSxcl5i79p3Sql7Od+J0t4L/VBSAMZferuKtBx2+K3IEEhBsHAgV7NJ+8GneynJq2ilKjgqR7A5cyiyMDlBWCRzUbjQ53PC6NletjMVWzuPIvTBFOGrEv4+AaRPVRgourlCdWrF+9VMU5B4ArjIidcZeSPxnKKs8f/gxC7Bz7H12usx3eyQeXYnDBViMaTZI9AZtwNKYKhkrsTUNd4VW3hW69JJ60c++0D2JIhqTxSkPBqhYgCSuWsXBxNBDPy1o9ix28/rTbEslf78702PPv2QvQDee9hpdXGNTWSCdhgPxj+FGFPfiE68Vea5cBGFA/dGh+KTP/PeLCT/D8Fkisof81FFpaFt/xwFYJX6lcUI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
